# Site settings
author: Amber Williams
title: Becoming a Software Engineer.
header-img: img/home-bg.png
email: awilliams1234@live.com
copyright_name: Amber Williams
description: > # this means to ignore newlines until "baseurl:"
  Choosing Technology
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Awilliams4321

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
